### ISSUE TITLE
Agenda: Governance, Jul 14 2020

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#313]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday Jul 14 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Keybase main lobby](http://keybase.io/team/grincoin). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * [x] Funding requests processed?
   * [x] Spending logs updated?
1. Documentation progress
1. Code of conduct progress
1. RFC & sub-teams update
1. Other questions

**Comment by johndavies24** [comment]
It may be worth revisiting announcing future HFs.  If we have reason to believe that future hardforks are inevitable because of already known reasons (e.g. some known things are missing and a lot of new tech is emerging) and time is necessary to implement these things, then we should communicate that and set people's expectations.  Maybe future dates are set for a time-frame more like 1-3 years?  I am not sure how to do this in a way that allows for flexibility and also reduces fork risks, maybe trigger fork X blocks after some UTXO held by core was spent?  Just an idea, but if we already know reasons that future HF will be necessary I think it would be best to set that expectation now.

If there are no known reasons to expect future hardforks then it is alright to keep everything as is and let new reasons arise organically.
