### ISSUE TITLE
Support attendee donations

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#7]
People attending Grincon0 should have the option to make a donation to Grin's general development fund.

Requirements:
1. Should be crypto only, to a designated wallet address. Possible multiple currency support, such as BTC, XMR, and ETH.
1. Should have a suggested donation amount, for example the equivalent of EUR 50 in the local crypto equivalent.

Nice to haves:
1. Some kind of interactive tracker/dashboard during the conference that displays funding received.
1. Some kind of notification (celebratory sound or something) whenever a donation is being made.

**Comment by 0xb100d** [comment]
The official grin multi-sig wallet could be one address, I know there was an ETH and XMR wallet yeast was using. Could just pull up blockexplorers on a screen for transparent ones and refresh it every 10 minutes.

Would be nice to have a sign possibly with QR codes so that everyone is aware donations are important.

**Comment by lehnberg** [comment]
Closing.
